server:
  port: 777
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/app_telegram_bot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update