package uz.pdp.apptelegrambot.enums;

public enum LangFields {
    BUTTON_MY_BOTS,
    BUTTON_LANG_SETTINGS,
    BUTTON_ADD_BOT,
    BUTTON_CONTACT_US,
    BUTTON_LANGUAGE_RUSSIAN,
    BUTTON_LANGUAGE_ENGLISH,
    BUTTON_LANGUAGE_UZBEK,

    //sending,
    HELLO,
    SELECT_LANGUAGE_TEXT,
    SUCCESSFULLY_CHANGED_LANGUAGE,

    //exceptions
    EXCEPTION_LANGUAGE,
    CONTACT_US_TEXT, PAID_GROUP_TEXT, BUTTON_ADMIN_PAYMENT_CLICK_TEXT, BUTTON_ADMIN_PAYMENT_PAYME_TEXT, BUTTON_ADMIN_PAYMENT_SCREENSHOT_TEXT, BUTTON_ADMIN_PAYMENT_CODE_TEXT, EXCEPTION_BUTTON
}
