package uz.pdp.apptelegrambot.enums;

public enum LangFields {
    MY_BOTS,
    LANG_SETTINGS,
    CONTACT_US,
    HELLO,
    BUTTON_LANGUAGE_RUSSIAN, BUTTON_LANGUAGE_ENGLISH, BUTTON_LANGUAGE_UZBEK, SELECT_LANGUAGE_TEXT, EXCEPTION_LANGUAGE, SUCCESSFULLY_CHANGED_LANGUAGE, ADD_BOT
}
