package uz.pdp.apptelegrambot.enums;

public enum LangFields {
    BUTTON_MY_BOTS,
    BUTTON_LANG_SETTINGS,
    BUTTON_ADD_BOT,
    BUTTON_CONTACT_US,
    BUTTON_LANGUAGE_RUSSIAN,
    BUTTON_LANGUAGE_ENGLISH,
    BUTTON_LANGUAGE_UZBEK,

    //sending,
    HELLO,
    SELECT_LANGUAGE_TEXT,
    SUCCESSFULLY_CHANGED_LANGUAGE,

    //exceptions
    EXCEPTION_LANGUAGE,
    CONTACT_US_TEXT, PAID_GROUP_TEXT, BUTTON_ADMIN_PAYMENT_CLICK_TEXT, BUTTON_ADMIN_PAYMENT_PAYME_TEXT, BUTTON_ADMIN_PAYMENT_SCREENSHOT_TEXT, BUTTON_ADMIN_PAYMENT_CODE_TEXT, SEND_BOT_TOKEN_TEXT, SEND_VALID_BOT_TOKEN_TEXT, SEND_CONTACT_NUMBER_TEXT, BUTTON_SEND_CONTACT_NUMBER, SEND_YOUR_PHONE_NUMBER_TEXT, ALREADY_TOKEN_SEND_US_TEXT, TARIFF_WEEK_TEXT, TARIFF_15_DAY_TEXT, TARIFF_MONTH_TEXT, TARIFF_YEAR_TEXT, TARIFF_UNLIMITED_TEXT, SELECT_TARIFF_TEXT, ACCEPT_TARIFFS_TEXT, NOT_ANY_TARIFF_TEXT, SEND_WEEKLY_TARIFF_PRICE_TEXT, SEND_DAY15_TARIFF_PRICE_TEXT, SEND_MONTHLY_TARIFF_PRICE_TEXT, SEND_YEAR_TARIFF_PRICE_TEXT, SEND_UNLIMITED_TARIFF_PRICE_TEXT,
    SUCCESSFULLY_ADDED_TARIFF_PRICE_TEXT,
    SEND_VALID_PRICE_FOR_TARIFF_TEXT, SELECT_CHOOSE_TARIFF_FOR_JOIN_TEXT, SEND_CODE_FOR_JOIN_REQ_TEXT, JOIN_REQ_CODE_INVALID_TEXT, JOIN_REQ_CODE_VALID_TEXT, SEND_MONEY_TO_CARD_AND_SEND_SCREENSHOT_TEXT, SECTION_DONT_WORK_TEXT, EXCEPTION_BUTTON
}
