package uz.pdp.apptelegrambot.enums;

public enum StateEnum {
    START,
    OWNER_SENDING_PHOTO,
    CHOOSE_PERMISSION,
    PERMISSION_EXPIRE,
    USE_CODE,
    CHOOSES_PAYMENT,
    ADMIN_SENDING_CONTACT,
    ADMIN_SENDING_TOKEN,
    ADMIN_SENDING_BOT_USERNAME,
    ADMIN_SENDING_SIZE_OF_REQUESTS,
    SIZE_OF_REQUESTS,
    ADMIN_SELECTING_PAYMENT,
    SENDING_CODE,
    SETTINGS_GROUP,
    SETTINGS_PAYMENT,
    SETTINGS_TARIFF,
    SENDING_TARIFF_NAME,
    SENDING_TARIFF_PRICE,
    SENDING_TARIFF_ORDER,
    SENDING_TARIFF_EXPIRE, SELECT_TARIFF, GENERATE_CODE_FOR_GROUP, MANAGE_TARIFF, SENDING_CARD_NUMBER_FOR_ONE, SELECT_GROUP_FOR_SCREENSHOT, ON_SCREENSHOTS, SENDING_CARD_NUMBER_FOR_ALL, CHANGE_TARIFF_PRICE, CHANGE_TARIFF_ORDER, CHANGE_TARIFF_NAME, CHANGE_TARIFF_EXPIRE,
}
